apiVersion: v1
kind: Pod
metadata:
  name: kube-scaler
spec:
  serviceAccountName: kube-scaler-sa
  containers:
    - name: mypod
      image: zhichenwang1103/kube-scaler:latest
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          value: "default"
        - name: REPLICAS
          value: "1"
        - name: USE_IN_CLUSTER_CLIENT
          value: "true"
        - name: RESOURCE_KIND
          value: "ARGO_ROLLOUT"
