apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: dev
spec:
  serviceAccountName: mysa
  containers:
    - name: mypod
      image: ghcr.io/chrisdevopsorg/kube-scaler:latest
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          value: "default"
        - name: REPLICAS
          value: "1"
        - name: USE_IN_CLUSTER_CLIENT
          value: "true"
        - name: RESOURCE_KIND
          value: "DEPLOYMENT"
