name: Build Docker Image
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
  pull_request:
      branches:
        - main
      paths-ignore:
        - 'README.md'
        - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-docker-build:
    name: Call Docker Build
    uses: ChrisDevOpsOrg/reusable-workflows/.github/workflows/docker-build.yaml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write

    secrets: inherit

    with:
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
          ghcr.io/${{ github.repository }}